### ISSUE TITLE
Group Creation

### ISSUE THREAD

**Issue by bflanagin** [OpenSeedINC/OpenSeed-Godot#14]
# Story

User needs to create a group in his Godot based ODESI powered game or application. 

# Tasks
- [x] Group functions need to be added to OpenSeed-Godot
- [x] Dialog box to create Group
* - [x] Group Title
* - [ ] Add users within connections list
* - [x] Accept or cancel buttons

- [ ] Add groups in connections lists.
