### ISSUE TITLE
Connection Requests

### ISSUE THREAD

**Issue by bflanagin** [OpenSeedINC/OpenSeed-Godot#17]
# Story

User 1: wants to connect with another ODESI user. They Search for a user, selects the user, and then sends a request

User 2: sees a pending request in their list of users and wants to find out who this user is and decide on how to proceed.

# Tasks
- [ ]  Add any missing functions in OpenSeed-Godot. 
- [x]  Create search window / dialog
* - [x]  List users noting user
* - [ ]  List groups noting group (only open groups)
* - [ ]  Select user and view profile
* - [ ]  Send Request
- [x] Create Connection Dialog
* - [x] Give basic information about user that wants to connect with User 2
* - [ ] Add ability to look at full profile
* - [x] Add ability to Accept / Deny connection
