### ISSUE TITLE
Update Cryptographic algorithm to match OpenSeed

### ISSUE THREAD

**Issue by bflanagin** [OpenSeedINC/OpenSeed-Godot#7]
#Story
User wants to use OpenSeed in a secure manor for obvious reasons. Right now everything comes back unintelligible. 

# Tasks
- [x] Using current OpenSeed code to rework algorithm.
- [x] Test with chat
- [x] Test with general app data
